[package]
name = "avro_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version="1.0.60",features=["full","fold"]}
quote = "1.0.8"
proc-macro2 = "1.0"
avro-rs = { path = "../avro" }
